<div class="um-membership-required">
	<h2>
		<span class="en"><?php echo pll_translate_string( 'Membership Required', 'en' ); ?></span>
		<span class="cn"><?php echo pll_translate_string( 'Membership Required', 'cn' ); ?></span>
		<span class="zh"><?php echo pll_translate_string( 'Membership Required', 'zh' ); ?></span>
	</h2>
	<p><span class="en"><?php echo pll_translate_string( 'You have reached the limit of 5 Premium articles, please','en'); ?></span><span class="cn"><?php echo pll_translate_string( 'You have reached the limit of 5 Premium articles, please','cn'); ?></span><span class="zh"><?php echo pll_translate_string( 'You have reached the limit of 5 Premium articles, please','zh'); ?></span> <a href="<?php echo get_permalink( UM()->options()->get( 'core_register' ) ); ?>?rid=<?php echo $_REQUEST['post_id']; ?>" style="text-transform: lowercase;"><span class="en"><?php echo pll_translate_string( 'Sign up','en'); ?></span><span class="cn"><?php echo pll_translate_string( 'Sign up','cn'); ?></span><span class="zh"><?php echo pll_translate_string( 'Sign up','zh'); ?></span></a> <span class="en"><?php echo pll_translate_string( 'for an account to enjoy full access.','en'); ?></span><span class="cn"><?php echo pll_translate_string( 'for an account to enjoy full access.','cn'); ?></span><span class="zh"><?php echo pll_translate_string( 'for an account to enjoy full access.','zh'); ?></span></p>
	<a href="<?php echo get_permalink( UM()->options()->get( 'core_login' ) ); ?>?rid=<?php echo $_REQUEST['post_id']; ?>" class="elementor-button"><span class="en"><?php echo pll_translate_string( 'Sign in','en'); ?></span><span class="cn"><?php echo pll_translate_string( 'Sign in','cn'); ?></span><span class="zh"><?php echo pll_translate_string( 'Sign in','zh'); ?></span></a>
</div>
<div class="um-membership-blur">
	<img src="<?php echo get_stylesheet_directory_uri().'/assets/images/blur-image.jpg'; ?>" style="width: 100%;display: block;margin-bottom: 30px;margin-top: 30px;">
	<p>Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci[ng] velit, sed quia non numquam [do] eius modi tempora inci[di]dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?”</p>

	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>